#!/usr/bin/env bash
set -eu
set -o pipefail

branch=${1:-master}
(cd /usr/local/share/puppet-tozt && sudo git pull && sudo git checkout "$branch" && sudo git reset --hard "origin/$branch")
sudo puppet apply --show_diff --modulepath=/usr/local/share/puppet-tozt/modules /usr/local/share/puppet-tozt/manifests
