#!/bin/sh
set -eu

conf_location="/usr/local/share/puppet-tozt"
conf_repo="https://github.com/doy/puppet-tozt"

mkdir -p "$conf_location"
cd "$conf_location" || exit 1
git clone "$conf_repo" .
git submodule update --init --recursive
cp -r /tmp/secrets/ modules/secret/files

set +e
puppet apply --modulepath=./modules --hiera_config=./hiera/hiera.yaml --detailed-exitcodes manifests
puppet_exit=$?
if [ $puppet_exit -eq 2 ]; then
  exit 0
else
  exit $puppet_exit
fi
