#!/bin/sh
set -eu

restic backup \
    --repository-file=/etc/restic/repository \
    --password-file=/etc/restic/password \
    --exclude-caches \
    --exclude='/home/*/.cache' \
    --exclude='/home/*/.cargo' \
    --exclude='/home/*/.rustup' \
    --exclude='/home/doy/mnt' \
    --exclude='/home/doy/tmp' \
    --cache-dir='/var/cache/restic' \
    --one-file-system \
    --verbose \
    /home /etc /usr/local/bin <%= @extra_paths.join(" ") %>
restic forget \
    --repository-file=/etc/restic/repository \
    --password-file=/etc/restic/password \
    --cache-dir='/var/cache/restic' \
    --verbose \
    --keep-within-daily 7d \
    --keep-within-weekly 1m \
    --keep-within-monthly 1y \
    --keep-yearly unlimited \
    --keep-last 4 \
    --prune
