#!/usr/bin/env bash
set -eux
set -o pipefail

host="$1"

if ssh root@$host test ! -e /usr/bin/pacman; then
    ssh root@$host wget https://raw.githubusercontent.com/gh2o/digitalocean-debian-to-arch/debian9/install.sh -O install.sh
    ssh root@$host bash install.sh --i_understand_that_this_droplet_will_be_completely_wiped
    sleep 30
fi

ssh root@$host pacman --noconfirm -Sy
ssh root@$host pacman --noconfirm --needed -S puppet git ruby-shadow

if ssh root@$host test -d /tmp/bootstrap-tozt; then
    ssh root@$host "cd /tmp/bootstrap-tozt && git pull"
else
    ssh root@$host "cd /tmp && git clone git://github.com/doy/bootstrap-tozt"
fi

ssh root@$host "cd /tmp/bootstrap-tozt && puppet apply --modulepath=./modules manifest.pp"
