#!/usr/bin/env bash
set -eux
set -o pipefail

cd /tmp

git clone https://aur.archlinux.org/package-query.git
(
    cd package-query
    makepkg -si --noconfirm --needed
)

git clone https://aur.archlinux.org/yaourt.git
(
    cd yaourt
    makepkg -si --noconfirm --needed
)
