#!/usr/bin/env bash
set -eux
set -o pipefail

cd /tmp

su doy -c "git clone https://aur.archlinux.org/package-query.git"
(
    cd package-query
    su doy -c makepkg
    pacman -U --noconfirm --needed --asdeps package-query-*.pkg.tar.xz
)

su doy -c "git clone https://aur.archlinux.org/yaourt.git"
(
    cd yaourt
    su doy -c makepkg
    pacman -U --noconfirm --needed yaourt-*.pkg.tar.xz
)
