#!/bin/sh
set -eu
set -o pipefail

address="$(curl --connect-timeout 1 -s http://169.254.169.254/metadata/v1/interfaces/public/0/ipv4/address || true)"
if [ -n "$address" ]; then
    printf "bind_address=%s" "$address"
fi
