#!/usr/bin/env ruby

require 'date'
require 'json'

now = Time.now

snapshot_data = JSON.load(%x{sudo restic --repository-file=/etc/restic/repository --password-file=/etc/restic/password snapshots --json latest})[0]
stats_data = JSON.load(%x{sudo restic --repository-file=/etc/restic/repository --password-file=/etc/restic/password stats --json latest})
summary = snapshot_data["summary"]

backup_start = DateTime.iso8601(summary["backup_start"]).to_time
backup_end = DateTime.iso8601(summary["backup_end"]).to_time
ago_s = now - backup_end
dur_s = backup_end - backup_start
file_size_b = stats_data["total_size"]
file_count_n = stats_data["total_file_count"]

puts "restic days_since_last_run=#{ago_s / 60.0 / 60.0 / 24.0},last_run_duration_minutes=#{dur_s / 60.0},file_size=#{file_size_b}i,file_count=#{file_count_n}i"
