server_url: https://headscale.tozt.net
listen_addr: 0.0.0.0:8080
metrics_listen_addr: 0.0.0.0:9090
private_key_path: <%= @data_dir %>/private.key
noise:
  private_key_path: <%= @data_dir %>/noise_private.key
ip_prefixes:
  - 100.64.0.0/10
disable_check_updates: true
db_type: sqlite3
db_path: <%= @data_dir %>/db.sqlite
