server_url: https://headscale.tozt.net
listen_addr: 0.0.0.0:8081
metrics_listen_addr: 0.0.0.0:9091
private_key_path: <%= @data_dir %>/private.key
noise:
  private_key_path: <%= @data_dir %>/noise_private.key
ip_prefixes:
  - fd7a:115c:a1e0::/48
  - 100.64.0.0/10
disable_check_updates: true
db_type: sqlite3
db_path: <%= @data_dir %>/db.sqlite
dns_config:
  override_local_dns: false
  magic_dns: true
  base_domain: headscale.tozt.net
