#!/bin/sh
set -eux
set -o pipefail

puppet-tozt

sudo -E -u doy sh -c "cd ~/conf && git pull && make install"
sudo sh -c "cd ~/conf && git pull && make install"

sudo -u doy yay --noconfirm
sudo -u doy yay -Yc --noconfirm
<%= @extra_script %>
