#!/bin/sh
set -eux
set -o pipefail

sudo -vS

puppet-tozt

sudo -u doy sh -c "cd ~/conf && git pull && make install"
sudo sh -c "cd ~/conf && git pull && make install"

sudo -u doy yay --noconfirm --sudoflags=-S
sudo -u doy yay -Yc --noconfirm --sudoflags=-S
<%= @extra_script %>
