#!/usr/bin/env ruby

$config_dir = ENV['CERTBOT_CONFIG_DIR'] || '/etc/letsencrypt'

def run
  require 'openssl'

  (Dir.entries("#{$config_dir}/live/") - [".", ".."]).each do |site|
    cert = File.read("#{config_dir}/live/#{site}/cert.pem")
    x509 = OpenSSL::X509::Certificate.new(cert)
    days = (x509.not_after - Time.now) / 60 / 60 / 24
    sanitized_site = site.gsub(/[^a-zA-Z0-9]/, '_')
    puts "#{sanitized_site}.value #{days}"
  end
end

def config
  puts "graph_title cert age"
  puts "graph_category network"
  puts "graph_vlabel time until cert expiration (days)"
  puts "graph_args -l 0"
  puts "graph_scale no"

  (Dir.entries("#{$config_dir}/live/") - [".", ".."]).each do |site|
    sanitized_site = site.gsub(/[^a-zA-Z0-9]/, '_')
    puts "#{sanitized_site}.label #{site}"
    puts "#{sanitized_site}.warning 21:"
    puts "#{sanitized_site}.critical 7:"
  end
end

if $0 == __FILE__
  if ARGV[0] == "config"
    config
  else
    run
  end
end
