#!/usr/bin/env perl
use strict;
use warnings;
use 5.020;

my $sysfs_file = '/sys/block/md127/md/mismatch_cnt';
chomp(my $count = do { local $/; open my $fh, '<', $sysfs_file or die "couldn't open $sysfs_file"; <$fh> });
if ($count > 0) {
    die "saw a mismatch count of $count";
}
