#!/bin/sh
set -eu

if ! mount | grep -q /media/persistent; then
    exit 1
fi

date -Iseconds >/media/persistent/last_run_start

cleanup() {
    set +e
    umount /media/backup
    lvremove -y partofme/backup
    date -Iseconds >/media/persistent/last_run_end
}
trap cleanup EXIT

lvcreate --size 10G --snapshot --name backup /dev/partofme/data
mkdir -p /media/backup
mount -o ro /dev/partofme/backup /media/backup
rclone \
    --config /etc/rclone.conf \
    --exclude '/borg/**' \
    sync \
    --fast-list \
    /media/backup crypt:partofme
