#!/bin/sh

if ! mount | grep -q /media/persistent; then
    exit 1
fi

date -Iseconds >/media/persistent/last_run_start
sudo lvcreate --size 10G --snapshot --name backup /dev/partofme/data
sudo mkdir -p /media/backup
sudo mount -o ro /dev/partofme/backup /media/backup
rclone \
    --config /etc/rclone.conf \
    --exclude /borg/**
    sync \
    --fast-list \
    /media/backup crypt:partofme
sudo umount /media/backup
sudo lvremove -y partofme/backup
date -Iseconds >/media/persistent/last_run_end
