location:
    source_directories:
        - /home
        - /etc
        - /usr/local/bin
<%- @extra_paths.each do |path| -%>
        - <%= path %>
<%- end -%>
    repositories:
        - ssh://borg@<%= @borgmatic_host %>/./<%= @current_hostname %>
    atime: false
    exclude_patterns:
        - /home/*/.cache
        - /home/*/.cargo
        - /home/*/.rustup
        - /home/doy/coding/*/target
        - /home/doy/mnt
        - /home/doy/tmp

storage:
    encryption_passphrase: '<%= @escaped_borgmatic_passphrase %>'
    ssh_command: /usr/bin/ssh -i /etc/borgmatic/borg_ssh_key -o StrictHostKeyChecking=no

retention:
    keep_daily: 7
    keep_weekly: 4
    keep_monthly: 12
    keep_yearly: 1000
