#!/bin/bash
set -eu
set -o pipefail

cd /media/persistent
mkdir -p mail/tmp
dir=$(mktemp -d -p /media/persistent/mail/tmp learnspam.XXXXXXXX)
trap 'rm -rf $dir' EXIT

ham="${dir}/ham"
spam="${dir}/spam"
mkdir "$ham" "$spam"

container_dir="${dir#/media/persistent}"
container_ham="${container_dir}/ham"
container_spam="${container_dir}/spam"

find /media/persistent/mail -type f -mtime -90 | grep /cur/ | grep -v Sent | grep -v Junk | xargs -i ln {} "${dir}/ham"
find /media/persistent/mail -type f -mtime -90 | grep /cur/ | grep -v Sent | grep Junk | xargs -i ln {} "${dir}/spam"

docker-compose exec imap rspamc -h antispam:11334 -P mailu learn_ham "$container_ham"
docker-compose exec imap rspamc -h antispam:11334 -P mailu learn_spam "$container_spam"

docker-compose exec imap rspamc -h antispam:11334 -P mailu -f 13 fuzzy_add "$container_ham"
docker-compose exec imap rspamc -h antispam:11334 -P mailu -f 11 fuzzy_del "$container_ham"

docker-compose exec imap rspamc -h antispam:11334 -P mailu -f 11 fuzzy_add "$container_spam"
docker-compose exec imap rspamc -h antispam:11334 -P mailu -f 13 fuzzy_del "$container_spam"
