#!/usr/bin/env python3

from datetime import datetime, timezone
from pathlib import Path
import re

from cryptography import x509
from prometheus_client import CollectorRegistry, Gauge, generate_latest

NOW = datetime.now(timezone.utc)


def write_certbot_data(registry: CollectorRegistry):
    g = Gauge(
        "certbot_time_remaining",
        "Time left until certificate expires",
        ["site"],
        registry=registry,
    )
    for dir in Path("/media/persistent/certbot/live").iterdir():
        if not dir.is_dir():
            continue
        with open(dir / "cert.pem", "rb") as f:
            cert_data = f.read()
        cert = x509.load_pem_x509_certificate(cert_data)
        g.labels(site=re.sub("[^a-zA-Z0-9]", "_", dir.name)).set(
            (cert.not_valid_after_utc - NOW).total_seconds()
        )


def main():
    registry = CollectorRegistry()
    write_certbot_data(registry)
    print(generate_latest(registry).decode(), end="")


if __name__ == "__main__":
    main()
