#!/usr/bin/env python3

from datetime import datetime, timezone
import re

from prometheus_client import CollectorRegistry, Gauge, generate_latest

NOW = datetime.now(timezone.utc)


def find_raid_devices():
    with open("/proc/mdstat") as f:
        mdstat = f.readlines()
    return [
        re.sub(r" .*", "", line).rstrip()
        for line in mdstat
        if re.match(r"[a-z0-9]+ :", line)
    ]


def write_raid_scrub_check_data(registry: CollectorRegistry):
    g = Gauge(
        "raid_mismatch_cnt",
        "The value of /sys/block/<device>/md/mismatch_cnt",
        ["device"],
        registry=registry,
    )
    for device in find_raid_devices():
        with open(f"/sys/block/{device}/md/mismatch_cnt") as f:
            mismatch_cnt = f.read().strip()
        g.labels(device=device).set(int(mismatch_cnt))


def main():
    registry = CollectorRegistry()
    write_raid_scrub_check_data(registry)
    print(generate_latest(registry).decode(), end="")


if __name__ == "__main__":
    main()
