#!/bin/sh
set -eu

tmp="$(mktemp --tmpdir -d metabase-cron.XXXXXXXXXX)"

cleanup() {
    if perl -e'exit 1 unless $ARGV[0] =~ m{^/tmp/metabase-cron.*$}' "$tmp"; then
        rm -rf "$tmp"
    fi
}
trap cleanup EXIT

cd "$tmp"
su doy /home/doy/.cargo/bin/ynab-export

psql -U metabase ynab < schema.sql
psql -U metabase ynab -c 'COPY accounts FROM STDIN' < accounts.tsv
psql -U metabase ynab -c 'COPY category_groups FROM STDIN' < category_groups.tsv
psql -U metabase ynab -c 'COPY categories FROM STDIN' < categories.tsv
psql -U metabase ynab -c 'COPY months FROM STDIN' < months.tsv
psql -U metabase ynab -c 'COPY categories_by_month FROM STDIN' < categories_by_month.tsv
psql -U metabase ynab -c 'COPY payees FROM STDIN' < payees.tsv
psql -U metabase ynab -c 'COPY transactions FROM STDIN' < transactions.tsv
psql -U metabase ynab -c 'COPY subtransactions FROM STDIN' < subtransactions.tsv
psql -U metabase ynab -c 'COPY scheduled_transactions FROM STDIN' < scheduled_transactions.tsv
psql -U metabase ynab -c 'COPY scheduled_subtransactions FROM STDIN' < scheduled_subtransactions.tsv

seq 1000000 | psql -U metabase ynab -c 'COPY ints FROM STDIN'

# shellcheck disable=SC2046
su doy /home/doy/coding/investments-sheet-export/bin/load $(cat /home/doy/.config/google/investments-sheet) > /dev/null
