#!/bin/sh
set -eu

tmp="$(mktemp --tmpdir -d metabase-cron.XXXXXXXXXX)"

cleanup() {
    if perl -e'exit 1 unless $ARGV[0] =~ m{^/tmp/metabase-cron.*$}' "$tmp"; then
        rm -rf "$tmp"
    fi
}
trap cleanup EXIT

chown doy:doy "$tmp"
cd "$tmp"

# shellcheck disable=SC2046
sudo -u doy /home/doy/coding/metabase-utils/bin/load $(cat /home/doy/.config/google/investments-sheet) > /dev/null
