#!/bin/sh
set -eu
set -o pipefail

mkdir -p info/web
git for-each-ref --sort=committerdate --format='%(committerdate)' refs/heads | tail -n1 > info/web/last-modified

git push --all github
git push --tags github
git push --all gitlab
git push --tags gitlab
