#!/usr/bin/env bash
set -eu
set -o pipefail

(cd /usr/local/share/puppet-tozt && sudo git pull)
sudo puppet apply --show_diff --modulepath=/usr/local/share/puppet-tozt/modules -e 'include host::tozt'
